# Generated by Django 5.2.4 on 2025-07-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('signup_method', models.CharField(choices=[('manual', 'Manual'), ('google', 'Google'), ('phone', 'phone')], default='manual', max_length=20)),
            ],
        ),
    ]
