# Generated by Django 5.2.4 on 2025-07-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
