# Generated by Django 5.2.4 on 2025-08-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0003_alter_signup_username_alter_signup_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_name', models.CharField(max_length=255)),
                ('Artist_name', models.CharField(max_length=255)),
                ('Song_Image', models.URLField(max_length=255)),
                ('Song_Audio', models.FileField(upload_to='')),
            ],
        ),
    ]
