# Generated by Django 5.2.4 on 2025-08-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0004_songdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='songdetails',
            name='Song_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
