# Generated by Django 5.2.4 on 2025-08-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0005_remove_songdetails_id_songdetails_song_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRENDINGSong',
            fields=[
                ('Song_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Song_name', models.CharField(max_length=255)),
                ('Artist_name', models.CharField(max_length=255)),
                ('Song_Image', models.URLField(max_length=255)),
                ('Song_Audio', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='SongDetails',
        ),
    ]
