# Generated by Django 5.2.4 on 2025-08-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0006_trendingsong_delete_songdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_name', models.CharField(max_length=255)),
                ('Artist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Release_date', models.DateField(blank=True, null=True)),
                ('Artist_Image', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_Id', models.IntegerField()),
                ('Song_name', models.CharField(max_length=255)),
                ('Song_Audio', models.FileField(upload_to='ArtistAudio/')),
                ('Song_Image', models.URLField(max_length=255)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='Muser.album')),
            ],
        ),
    ]
