# Generated by Django 5.2.4 on 2025-08-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0007_album_albumsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Album_name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='Release_date',
        ),
    ]
