# Generated by Django 5.2.4 on 2025-08-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0008_remove_album_album_name_remove_album_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingsong',
            name='Album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Muser.album'),
        ),
    ]
