# Generated by Django 5.2.4 on 2025-08-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0009_trendingsong_album'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='AlbumSong',
            new_name='ArtistSong',
        ),
    ]
