# Generated by Django 5.2.4 on 2025-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0010_rename_album_artist_rename_albumsong_artistsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Artist_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
