# Generated by Django 5.2.4 on 2025-08-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0011_alter_artist_artist_name_alter_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsong',
            name='Song_Audio',
            field=models.FileField(upload_to=''),
        ),
    ]
