# Generated by Django 5.2.4 on 2025-08-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0012_alter_artistsong_song_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Album_name', models.CharField(max_length=255)),
                ('Album_Image', models.URLField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='artistsong',
            old_name='Album',
            new_name='Artist',
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_Id', models.IntegerField()),
                ('Song_name', models.CharField(max_length=255)),
                ('Song_Audio', models.FileField(upload_to='')),
                ('Song_Image', models.URLField(max_length=255)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='Muser.album')),
            ],
        ),
    ]
