# Generated by Django 5.2.4 on 2025-08-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0013_album_rename_album_artistsong_artist_albumsong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingsong',
            old_name='Album',
            new_name='Artist',
        ),
    ]
