# Generated by Django 5.2.4 on 2025-08-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0014_rename_album_trendingsong_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingsong',
            name='Album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Muser.album'),
        ),
    ]
