# Generated by Django 5.2.4 on 2025-08-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0015_trendingsong_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingsong',
            name='Album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_songs', to='Muser.album'),
        ),
        migrations.AlterField(
            model_name='trendingsong',
            name='Artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_songs', to='Muser.artist'),
        ),
    ]
