# Generated by Django 5.2.4 on 2025-08-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0016_alter_trendingsong_album_alter_trendingsong_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumsong',
            name='id',
        ),
        migrations.AddField(
            model_name='artistsong',
            name='external_artist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trendingsong',
            name='external_album_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trendingsong',
            name='external_artist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albumsong',
            name='Song_Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
