# Generated by Django 5.2.4 on 2025-08-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0017_remove_albumsong_id_artistsong_external_artist_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistsong',
            name='external_artist_id',
        ),
        migrations.RemoveField(
            model_name='trendingsong',
            name='Album',
        ),
        migrations.RemoveField(
            model_name='trendingsong',
            name='Artist',
        ),
        migrations.RemoveField(
            model_name='trendingsong',
            name='external_album_id',
        ),
        migrations.RemoveField(
            model_name='trendingsong',
            name='external_artist_id',
        ),
        migrations.AddField(
            model_name='albumsong',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='albumsong',
            name='Song_Id',
            field=models.IntegerField(),
        ),
    ]
