# Generated by Django 5.2.4 on 2025-08-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0018_remove_artistsong_external_artist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsong',
            name='Song_Audio',
            field=models.FileField(upload_to='AlbumSong'),
        ),
        migrations.AlterField(
            model_name='artistsong',
            name='Song_Audio',
            field=models.FileField(upload_to='ArtistSong'),
        ),
    ]
