# Generated by Django 5.2.4 on 2025-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0019_alter_albumsong_song_audio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarathiSong',
            fields=[
                ('Song_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Song_name', models.CharField(max_length=255)),
                ('Artist_name', models.CharField(max_length=255)),
                ('Song_Image', models.URLField(max_length=255)),
                ('Song_Audio', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PopularSong',
            fields=[
                ('Song_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Song_name', models.CharField(max_length=255)),
                ('Artist_name', models.CharField(max_length=255)),
                ('Song_Image', models.URLField(max_length=255)),
                ('Song_Audio', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TamilSong',
            fields=[
                ('Song_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Song_name', models.CharField(max_length=255)),
                ('Artist_name', models.CharField(max_length=255)),
                ('Song_Image', models.URLField(max_length=255)),
                ('Song_Audio', models.FileField(upload_to='')),
            ],
        ),
    ]
