# Generated by Django 5.2.4 on 2025-08-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0020_marathisong_popularsong_tamilsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathisong',
            name='Song_Audio',
            field=models.FileField(upload_to='MarathiSong'),
        ),
        migrations.AlterField(
            model_name='popularsong',
            name='Song_Audio',
            field=models.FileField(upload_to='PopularSong'),
        ),
        migrations.AlterField(
            model_name='tamilsong',
            name='Song_Audio',
            field=models.FileField(upload_to='TamilSong'),
        ),
        migrations.AlterField(
            model_name='trendingsong',
            name='Song_Audio',
            field=models.FileField(upload_to='TrendingSong'),
        ),
    ]
