# Generated by Django 5.2.4 on 2025-08-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0021_alter_marathisong_song_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='signup_method',
        ),
    ]
