# Generated by Django 5.2.4 on 2025-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0022_remove_signup_signup_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
