# Generated by Django 5.2.4 on 2025-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0026_artist_listener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
