# Generated by Django 5.2.4 on 2025-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0028_alter_signup_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
