# Generated by Django 5.2.4 on 2025-08-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0029_alter_signup_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
