# Generated by Django 5.2.4 on 2025-09-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muser', '0031_album_listener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
